import fs from "node:fs";
import path from "node:path";
import { callSignor } from "../engine.mjs";
import { atomicWriteFileSync } from "../atomic.mjs";
import { recordArtifact } from "../db.mjs";
import { handleDebate } from "./debate.mjs";
import { BRAND, resolveConfigDir } from "../brand.mjs";

export async function handlePlan(taskDescription, config, options = {}) {
  const cwd = process.cwd();

  // If --debate flag is present, delegate directly to Debate Engine
  if (Array.isArray(taskDescription) && taskDescription.includes("--debate")) {
    const debateArgs = taskDescription.filter(t => t !== "--debate");
    return await handleDebate(debateArgs, config);
  }
  if (typeof taskDescription === "string" && taskDescription.includes("--debate")) {
    const debateArgs = taskDescription.replace("--debate", "").trim().split(/\s+/);
    return await handleDebate(debateArgs, config);
  }

  // Check inputs
  let task = Array.isArray(taskDescription) ? taskDescription.join(" ") : taskDescription;
  if (!task || task.trim() === "") {
    const configDir = resolveConfigDir(cwd);
    const candidate0 = path.join(configDir, "plan_input.txt");
    const candidate1 = path.join(cwd, ".signor", "plan_input.txt");
    const candidate2 = path.join(cwd, "sol", "plan_input.txt");
    if (fs.existsSync(candidate0)) {
      task = fs.readFileSync(candidate0, "utf-8").trim();
    } else if (fs.existsSync(candidate1)) {
      task = fs.readFileSync(candidate1, "utf-8").trim();
    } else if (fs.existsSync(candidate2)) {
      task = fs.readFileSync(candidate2, "utf-8").trim();
    }
  }

  if (!task || task.trim() === "") {
    console.error(`\n❌ Usage: ${BRAND.bin} plan "<task description>" or provide .signor/plan_input.txt\n`);
    process.exit(1);
  }

  console.log(`\n📐 [${BRAND.name} Lead Architect] Formulating plan...`);
  console.log(`   Model:  \x1b[36m${config.model}\x1b[0m`);
  console.log(`   Effort: \x1b[33m${config.effort}\x1b[0m`);
  console.log(`   Task:   "${task.slice(0, 100)}..."\n`);

  const systemPrompt = `You are ${BRAND.name}, ${BRAND.personaTitle}.
You have access to native tools (view_file, search_code, list_directory) to inspect the project before making architectural decisions.
Your mandate:
1. Deliver comprehensive, deeply technical, step-by-step master architectural plans in Arabic for the engineer (Antigravity) to implement.
2. Invariant: 100% production-readiness, zero static mock data, full database modeling, and strict error handling.
3. If you need to verify an existing file or schema, use your tools before finalizing the plan.`;

  const userPrompt = `المهمة المعمارية والتخطيطية المطلوبة:
${task}

قم بفحص ملفات المشروع وهيكليته بدقة تامة عبر أدواتك، ثم اكتب خطة معمارية وتنفيذية شاملة ومفصلة بصيغة Markdown باللغة العربية تتضمن:
1. التوصيف الفني للمهمة والهدف المعماري
2. البنية الحالية والملفات المعنية
3. خطوات التنفيذ التفصيلية خطوة بخطوة مع أسماء الملفات والدوال
4. خطة الفحص والتحقق الصارم لضمان الجودة وعدم وجود أي Mock Data`;

  const start = Date.now();
  try {
    const plan = await callSignor([
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ], {
      enableTools: true,
      projectDir: cwd,
      noStdout: false,
    }, config);

    // Save outputs
    const configDir = resolveConfigDir(cwd, true);
    const plansDir = path.join(configDir, "plans");
    if (!fs.existsSync(plansDir)) fs.mkdirSync(plansDir, { recursive: true });

    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const archivePlanPath = path.join(plansDir, `plan-${timestamp}.md`);
    const planFileName = fs.existsSync(path.join(configDir, "signor_plan.md")) ? "signor_plan.md" : BRAND.planArtifact;
    const mainPlanPath = path.join(configDir, planFileName);
    const relPlanPath = path.relative(cwd, mainPlanPath);

    const fullMarkdown = `# الخطة المعمارية الشاملة — ${BRAND.name} (Lead Architect)\n\n- **التاريخ:** ${new Date().toLocaleString("ar-EG")}\n- **النموذج:** \`${config.model}\`\n- **مستوى الجهد:** \`${config.effort}\`\n- **المهمة:** ${task}\n\n---\n\n${plan}\n`;

    atomicWriteFileSync(archivePlanPath, fullMarkdown);
    atomicWriteFileSync(mainPlanPath, fullMarkdown);

    try { recordArtifact(null, "plan", relPlanPath, mainPlanPath, cwd); } catch {}

    // Also mirror to sol/sol_plan.md if sol directory exists
    const solDir = path.join(cwd, "sol");
    if (fs.existsSync(solDir)) {
      atomicWriteFileSync(path.join(solDir, "sol_plan.md"), fullMarkdown);
    }

    console.log(`\n\n✅ Plan successfully generated by ${BRAND.name} in ${Date.now() - start}ms!`);
    console.log(`📄 Saved to: ${relPlanPath}`);
    console.log(`📁 Archive copy: ${path.relative(cwd, archivePlanPath)}\n`);
  } catch (err) {
    console.error("\n❌ Failed to generate plan:", err.message);
    process.exit(1);
  }
}
