import fs from "node:fs";
import path from "node:path";
import { callSignor } from "../engine.mjs";
import { atomicWriteFileSync } from "../atomic.mjs";
import { recordArtifact } from "../db.mjs";

export async function handlePlan(taskDescription, config, options = {}) {
  const cwd = process.cwd();

  // Check inputs
  let task = taskDescription;
  if (!task || task.trim() === "") {
    const candidate1 = path.join(cwd, ".signor", "plan_input.txt");
    const candidate2 = path.join(cwd, "sol", "plan_input.txt");
    if (fs.existsSync(candidate1)) {
      task = fs.readFileSync(candidate1, "utf-8").trim();
    } else if (fs.existsSync(candidate2)) {
      task = fs.readFileSync(candidate2, "utf-8").trim();
    }
  }

  if (!task || task.trim() === "") {
    console.error(`\n❌ Usage: signor plan "<task description>" or provide .signor/plan_input.txt\n`);
    process.exit(1);
  }

  console.log(`\n📐 [Signor Lead Architect] Formulating plan...`);
  console.log(`   Model:  \x1b[36m${config.model}\x1b[0m`);
  console.log(`   Effort: \x1b[33m${config.effort}\x1b[0m`);
  console.log(`   Task:   "${task.slice(0, 100)}..."\n`);

  const systemPrompt = `You are Signor, Lead Software Architect & Principal Engineering Director.
You have access to native tools (view_file, search_code, list_directory) to inspect the project before making architectural decisions.
Your mandate:
1. Deliver comprehensive, deeply technical, step-by-step master architectural plans in Arabic for the engineer (Antigravity) to implement.
2. Invariant: 100% production-readiness, zero static mock data, full database modeling, and strict error handling.
3. If you need to verify an existing file or schema, use your tools before finalizing the plan.`;

  const userPrompt = `المهمة المعمارية والتخطيطية المطلوبة:
${task}

قم بفحص ملفات المشروع وهيكليته بدقة تامة عبر أدواتك، ثم اكتب خطة معمارية وتنفيذية شاملة ومفصلة بصيغة Markdown باللغة العربية تتضمن:
1. التوصيف الفني للمهمة والهدف المعماري
2. البنية الحالية والملفات المعنية
3. خطوات التنفيذ التفصيلية خطوة بخطوة مع أسماء الملفات والدوال
4. خطة الفحص والتحقق الصارم لضمان الجودة وعدم وجود أي Mock Data`;

  const start = Date.now();
  try {
    const plan = await callSignor([
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ], {
      enableTools: true,
      projectDir: cwd,
      noStdout: false,
    }, config);

    // Save outputs
    const signorDir = path.join(cwd, ".signor");
    const plansDir = path.join(signorDir, "plans");
    if (!fs.existsSync(plansDir)) fs.mkdirSync(plansDir, { recursive: true });

    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const archivePlanPath = path.join(plansDir, `plan-${timestamp}.md`);
    const mainPlanPath = path.join(signorDir, "signor_plan.md");

    const fullMarkdown = `# الخطة المعمارية الشاملة — Signor Lead Architect\n\n- **التاريخ:** ${new Date().toLocaleString("ar-EG")}\n- **النموذج:** \`${config.model}\`\n- **مستوى الجهد:** \`${config.effort}\`\n- **المهمة:** ${task}\n\n---\n\n${plan}\n`;

    atomicWriteFileSync(archivePlanPath, fullMarkdown);
    atomicWriteFileSync(mainPlanPath, fullMarkdown);

    try { recordArtifact(null, "plan", ".signor/signor_plan.md", mainPlanPath, cwd); } catch {}

    // Also mirror to sol/sol_plan.md if sol directory exists
    const solDir = path.join(cwd, "sol");
    if (fs.existsSync(solDir)) {
      atomicWriteFileSync(path.join(solDir, "sol_plan.md"), fullMarkdown);
    }

    console.log(`\n\n✅ Plan successfully generated by Signor in ${Date.now() - start}ms!`);
    console.log(`📄 Saved to: .signor/signor_plan.md`);
    console.log(`📁 Archive copy: .signor/plans/plan-${timestamp}.md\n`);
  } catch (err) {
    console.error("\n❌ Failed to generate plan:", err.message);
    process.exit(1);
  }
}
